when:
  - event: [push, pull_request, tag]

steps:
  lint:
    image: golangci/golangci-lint:v2.8-alpine
    environment:
      XDG_CACHE_HOME: /tmp/.cache
    commands:
      - golangci-lint run

  test:
    image: golang:1.25
    environment:
      GOCACHE: /tmp/.gocache
    commands:
      - go test ./...

  build:
    image: golang:1.25
    environment:
      GOCACHE: /tmp/.gocache
    commands:
      - CGO_ENABLED=0 go build -trimpath -o ip-detect ./cmd/ip-detect

  docker:
    image: woodpeckerci/plugin-docker-buildx:6
    settings:
      username:
        from_secret: DOCKER_LOGIN
      password:
        from_secret: DOCKER_TOKEN
      repo:
        from_secret: DOCKER_REPO
      dockerfile: Dockerfile
      tags:
        - ${CI_COMMIT_TAG}
        - latest
    when:
      - event: tag
